# Generated by Django 4.0.5 on 2022-06-08 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default=None, max_length=500)),
                ('name', models.CharField(default=None, max_length=50)),
                ('age', models.PositiveIntegerField(default=None)),
                ('school', models.CharField(default=None, max_length=50)),
                ('gender', models.CharField(default=None, max_length=30)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=6)),
            ],
        ),
    ]
