# Generated by Django 4.0.5 on 2022-06-09 20:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=200), size=6),
        ),
    ]
