# Generated by Django 4.0.5 on 2022-06-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('swipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipe',
            name='exchange_social_media',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='is_match',
        ),
        migrations.AddField(
            model_name='swipe',
            name='match_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='matches.match'),
        ),
    ]
