# Generated by Django 4.0.5 on 2022-06-09 16:22

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('profile_image', models.CharField(default='https://res.cloudinary.com/drgegagha/image/upload/v1654545117/shibr/image-b-large_in19xb.png', max_length=300)),
                ('karma', models.PositiveIntegerField(default=0)),
                ('interested_in', models.CharField(blank=True, max_length=30)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('max_age', models.PositiveIntegerField(default=20)),
                ('show_me', models.BooleanField(default=False)),
                ('give_social', models.BooleanField(default=False)),
                ('ig', models.CharField(blank=True, max_length=30)),
                ('sc', models.CharField(blank=True, max_length=30)),
                ('tw', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
