# Generated by Django 4.0.5 on 2022-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_profile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
