# Generated by Django 4.0.5 on 2022-06-09 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_image_index', models.IntegerField(default=None)),
                ('best_image_comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
                ('worst_image_index', models.IntegerField(default=None)),
                ('worst_image_comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
                ('bio_overall', models.CharField(default=None, max_length=30)),
                ('bio_good_comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
                ('bio_bad_comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
            ],
        ),
    ]
