# Generated by Django 4.0.5 on 2022-06-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('swipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='swipe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='swipes.swipe'),
        ),
    ]
